path_classifiers:
  docs:
    - exclude: / # ignore default classification for documentation
    - Documentation/
  generated:
    - exclude: / # ignore default classification for generated code
  library:
    - exclude: / # ignore default classification for library code
    - Resources/Public/Javascript/jPlayer
    - Resources/Public/Javascript/jQuery
    - Resources/Public/Javascript/jQueryUI
    - Resources/Public/Javascript/OpenLayers
  template:
    - exclude: / # ignore default classification for templates
    - Resources/Private/Templates
  test:
    - exclude: / # ignore default classification for test code
    - Tests/
